# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: bandlabtest

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

custom:
  commentBucket: comments-inbox

provider:
  name: aws
  runtime: nodejs4.3
  cfLogs: true
  iamRoleStatements:
    $ref: ./iamRoleStatements.json

stage: dev

functions:
  getComment:
    handler: handler.getComment
    events:
      - http:
          path: comments/{id}
          method: get 
          integration: lambda
          request:
            parameters:
              paths:
                id: true
  commentParser:
      handler: handler.commentParser
      events:
        - s3:
            bucket: ${self:custom.commentBucket}
            event: s3:ObjectCreated:*

resources:
  Resources:
    InboxS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.commentBucket}

plugins:
  - serverless-offline